version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile-server
    image: server
    container_name: server
    env_file:
      - ~/env.list
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: dockerfile-nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
