spring:
  application:
    name: claco
  profiles:
    active:
      - prod
    group:
      local:
        - local
      prod:
        - prod
    include:
      - oauth
      - aws
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: main-server
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m
